# Generated by Django 5.0 on 2024-01-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_rename_contact_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='contact1',
        ),
    ]
