# Generated by Django 5.0 on 2024-01-01 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_alter_product1_pimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product1',
            old_name='pcategory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='pdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='pimage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='pprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product1',
            old_name='psubcategory',
            new_name='subcategory',
        ),
    ]
