# Generated by Django 5.0 on 2024-01-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_rename_pcategory_product1_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_json', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('payment_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='orderupdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('update_desc', models.CharField(max_length=300)),
                ('delivered', models.BooleanField()),
                ('timestamp', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='product1',
            name='category',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='product1',
            name='subcategory',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
